class Autogenerated {
  int code;
  String message;
  CoinListData data;

  Autogenerated({this.code, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    message = json['message'];
    data = json['data'] != null ? new CoinListData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class CoinListData {
  List<Transactions> transactions;
  int coin;
  int eqMoney;
  Pagination pagination;

  CoinListData({this.transactions, this.coin, this.eqMoney, this.pagination});

  CoinListData.fromJson(Map<String, dynamic> json) {
    if (json['transactions'] != null) {
      transactions = new List<Transactions>();
      json['transactions'].forEach((v) {
        transactions.add(new Transactions.fromJson(v));
      });
    }
    coin = json['coin'];
    eqMoney = json['eq_money'];
    pagination = json['pagination'] != null
        ? new Pagination.fromJson(json['pagination'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.transactions != null) {
      data['transactions'] = this.transactions.map((v) => v.toJson()).toList();
    }
    data['coin'] = this.coin;
    data['eq_money'] = this.eqMoney;
    if (this.pagination != null) {
      data['pagination'] = this.pagination.toJson();
    }
    return data;
  }
}

class Transactions {
  String date;
  List<CoinListItem> list;

  Transactions({this.date, this.list});

  Transactions.fromJson(Map<String, dynamic> json) {
    date = json['date'];
    if (json['list'] != null) {
      list = new List<CoinListItem>();
      json['list'].forEach((v) {
        list.add(new CoinListItem.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['date'] = this.date;
    if (this.list != null) {
      data['list'] = this.list.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class CoinListItem {
  int id;
  String desc;
  int amount;
  int type;
  String createdAt;

  CoinListItem({this.id, this.desc, this.amount, this.type, this.createdAt});

  CoinListItem.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    desc = json['desc'];
    amount = json['amount'];
    type = json['type'];
    createdAt = json['created_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['desc'] = this.desc;
    data['amount'] = this.amount;
    data['type'] = this.type;
    data['created_at'] = this.createdAt;
    return data;
  }
}

class Pagination {
  int total;
  int current;
  int pageSize;
  bool hasNextPage;

  Pagination({this.total, this.current, this.pageSize, this.hasNextPage});

  Pagination.fromJson(Map<String, dynamic> json) {
    total = json['total'];
    current = json['current'];
    pageSize = json['pageSize'];
    hasNextPage = json['hasNextPage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total'] = this.total;
    data['current'] = this.current;
    data['pageSize'] = this.pageSize;
    data['hasNextPage'] = this.hasNextPage;
    return data;
  }
}